#!/usr/bin/env bash
#
#  install-gyb
#
#  Copyright (c) 2016, 2018 Stephen Whittle  All rights reserved.
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"),
#  to deal in the Software without restriction, including without limitation
#  the rights to use, copy, modify, merge, publish, distribute, sublicense,
#  and/or sell copies of the Software, and to permit persons to whom
#  the Software is furnished to do so, subject to the following conditions:
#  The above copyright notice and this permission notice shall be included
#  in all copies or substantial portions of the Software.
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
#  IN THE SOFTWARE.

##################################################
swift_install_dir() {
##################################################
    local dir=""

    for dir in $(printf "$PATH" | \
                 tr ':' \
                    ' ')
    do
        if [[ -x "$dir/swift" ]] ; then
            dir="$dir"
            break
        fi
    done

    printf "$dir"
}

##################################################
# main() {
##################################################

if [[ $(id -u) -ne 0 ]] ; then
    printf "you must be a superuser!!!\n" >&2
    exit 1
fi

url="https://github.com/apple/swift/raw/master/utils"
install_dir="$(swift_install_dir)"

if [[ -z "$install_dir" ]] || [[ ! -d "$install_dir" ]] ; then
    printf "unable to determine swift installation directory!!!\n" >&2
    exit 2
fi

apt-get update
rc=$?

[[ $rc -ne 0 ]] && exit $rc

apt-get install -y wget
rc=$?

[[ $rc -ne 0 ]] && exit $rc

for fname in "gyb" "gyb.py"
do
    if [[ ! -f "$install_dir/$fname" ]] ; then
        wget "$url/$fname"
        rc=$?

        [[ $rc -ne 0 ]] && exit $rc

        mv "$fname" "$install_dir"
        rc=$?

        [[ $rc -ne 0 ]] && exit $rc
    fi
done

chmod 755 "$install_dir/gyb"
rc=$?

[[ $rc -ne 0 ]] && exit $rc

gyb_source_file="$install_dir/gyb-source"
if [[ ! -x "$gyb_source_file" ]] ; then
    (
        printf "#!/usr/bin/env bash\n"
        printf "\n"
        printf "gyb_extension=\".gyb\"\n"
        printf "\n"
        printf "for gyb_file in \$(find \".\" -name \"*\$gyb_extension\" | sort)\n"
        printf "do\n"
        printf "    src_file=\"\$(printf \"%s/%s\" \"\$(dirname \"\$gyb_file\")\" \"\$(basename \"\$gyb_file\" \"\$gyb_extension\")\")\"\n"
        printf "\n"
        printf "    if [[ \"\$gyb_file\" -nt \"\$src_file\" ]] ; then\n"
        printf "        printf \"%s -> %s\n\" \"\$gyb_file\" \"\$src_file\" >&1\n"
        printf "\n"
        printf "        gyb --line-directive '' -o \"\$src_file\" \"\$gyb_file\"\n"
        printf "    fi\n"
        printf "done\n"
        printf "\n"
        printf "exit 0\n"
    ) >"$gyb_source_file"

    chmod 755 "$gyb_source_file"
    rc=$?

    [[ $rc -ne 0 ]] && exit $rc
fi

##################################################
exit 0
# }
##################################################
